### ISSUE TITLE
How to Modify B-Msn to add 2 functionalities

### ISSUE THREAD

**Issue by jr0driguezv** [ozcandegirmenci/B-Msn#2]
Hello dear friend Ozca, I hope you are well as well as your family.

My name is Joel, I am writing to you because a few days ago I have been looking at your project "B-Msn", first to thank you for sharing it is very useful, I know that you developed it a long time ago, I am trying to adapt it to my needs, however there are things that I have not been able to achieve.

1- When the user logs in I would like to send a UserNameFull as an additional parameter, I have tried to modify the Parameter.cs class by adding the following:

```
private T _Value2 = default (T);

public T Value2
{
      get {return _Value2; }
      set
      {
          // OnValueChanging (value);
          _Value2 = value;
      }
}

public Parameter (string name, T value, T value2): this (name)
{
       Value = value;
       Value2 = value2;
}
```

When I am logging in I provide the value for this field:
`command.Parameters.Add (new ParameterString ("un", txtUsername.Text, txtUserNameFull.Text));`

But after logging in where I get the parameter:
`ParameterString un = command.Parameters ["un"] as ParameterString;`

The Value2 is null, and when I am debugging at the moment of sending it as a parameter it has its value correctly.

```
/// Here comes Null
item.SubItems.Add (a.Value2);
```

2 - I would like to use a single window for the chat, and not a separate window for each chat, that is, in a sale the list of connected users is shown, and when clicking on one of them, they are shown on the right side the messages of the selected user, if I select another user, his chat will be shown, without having to have a separate window for each one. I know this requires a lot of modification in the inner class "MessagingSessionsManager".

I would be very grateful if you could give me some guidance to achieve these two goals.

**Comment by ozcandegirmenci** [comment]
Hi jr0driguezv,

Sorry about the late answer, I just saw your questions and guess that it is very late but let me answer your questions anyway.

1 - The problem with you FullName issue is, you are trying to use ParameterString parameter class which is designed to send a parameter name and a parameter value by default. You are trying to add a second value option to it.
To achieve your goal you have different ways;
a - You can send client's fullname as a new parameterstring which is added to commands that are going to transfer to the clients.
```c#
NetCommand command2 = new NetCommand(CommandNames.U_LOGIN);
command2.Parameters.Add(new ParameterInt32("hash", Server.Clients[i].HashCode));
command2.Parameters.Add(new ParameterInt32("st", Convert.ToInt32(Server.Clients[i].Status)));
command2.Parameters.Add(new ParameterString("un", Server.Clients[i].Username));
command2.Parameters.Add(new ParameterString("fullName", Server.Clients[i].FullName)); // this property does not exist at the moment, you need to manage it
``` 
b - You can create a new type of parameter by deriving it from the existing ones. For creating a paraemter which has two strings, derive a parameter from the ParameterString and overload its Write and Read properties. In this overloaded methods you have to Write your second parameter value to the Stream and also you have read it back from the stream.

2 - As you said to make a chat room feature you have to make some changes in the MessagingSessionManager class. In this class currently it is opening a new window for each chat session, but instead of opening a new form for each session, you have to open a sinle window during login. From that point you have to put all the messages that comes from server into this window. By the way you also have to make some changes in the server side. This change will be something like, you have to write a new server operation (SendMessageToAll) which redirects the message to the all clients which are connected at the moment. Also in the client side you have to listen for the server command (SendMessageToAll) and when this command recived put the message to the chat screen.

Hope these answers will help you

Regards
Ozcan

**Comment by jr0driguezv** [comment]
Good morning, I hope you are well!

Ozcan,
I have tried to make the modifications, but I haven't been successful. Anyway, thank you very much for taking the time to respond to the email; it is appreciated.

Merry Christmas, and I hope you have a great year.

Saludos Cordiales.!

[Firma Correo JRV]
Este mensaje y los documentos adjuntos contienen información confidencial. Si no es el destinatario, no puede leer, copiar, distribuir o utilizar esta información. Si ha recibido esta correspondencia por error, por favor póngase en contacto con el remitente y favor eliminar todas las copias.

This message and the attached documents contain Confidential Information. If you are not the intended recipient, you may not read, copy, distribute or use this information. If you received this correspondence in error, please contact the sender and delete all copies.

De: Ozcan Degirmenci ***@***.***>
Enviado el: domingo, 10 de diciembre de 2023 5:48 a.m.
Para: ozcandegirmenci/B-Msn ***@***.***>
CC: J. Rodríguez ***@***.***>; Author ***@***.***>
Asunto: Re: [ozcandegirmenci/B-Msn] How to Modify B-Msn to add 2 functionalities (Issue #2)


Hi jr0driguezv,

Sorry about the late answer, I just saw your questions and guess that it is very late but let me answer your questions anyway.

1 - The problem with you FullName issue is, you are trying to use ParameterString parameter class which is designed to send a parameter name and a parameter value by default. You are trying to add a second value option to it.
To achieve your goal you have different ways;
a - You can send client's fullname as a new parameterstring which is added to commands that are going to transfer to the clients.

NetCommand command2 = new NetCommand(CommandNames.U_LOGIN);

command2.Parameters.Add(new ParameterInt32("hash", Server.Clients[i].HashCode));

command2.Parameters.Add(new ParameterInt32("st", Convert.ToInt32(Server.Clients[i].Status)));

command2.Parameters.Add(new ParameterString("un", Server.Clients[i].Username));

command2.Parameters.Add(new ParameterString("fullName", Server.Clients[i].FullName)); // this property does not exist at the moment, you need to manage it

b - You can create a new type of parameter by deriving it from the existing ones. For creating a paraemter which has two strings, derive a parameter from the ParameterString and overload its Write and Read properties. In this overloaded methods you have to Write your second parameter value to the Stream and also you have read it back from the stream.

2 - As you said to make a chat room feature you have to make some changes in the MessagingSessionManager class. In this class currently it is opening a new window for each chat session, but instead of opening a new form for each session, you have to open a sinle window during login. From that point you have to put all the messages that comes from server into this window. By the way you also have to make some changes in the server side. This change will be something like, you have to write a new server operation (SendMessageToAll) which redirects the message to the all clients which are connected at the moment. Also in the client side you have to listen for the server command (SendMessageToAll) and when this command recived put the message to the chat screen.

Hope these answers will help you

Regards
Ozcan
